# Based on @simonw's action here:
# https://github.com/simonw/simonw

name: Update README

on:
  workflow_dispatch:
  # Runs once a day
  schedule:
    - cron: '0 11 * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Update README
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          python update_readme.py
          cat README.md

      - name: Commit and push if changed
        run: |-
          git diff
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "readme-bot"
          git add -A
          git diff-index --quiet HEAD || git commit -m "🤖  docs: Automated languages update" -m "Automated README top languages update using GitHub Actions."
          git push
